export enum OrderSocketEvent {
  newOrder = "new-order",
  createOrder = "create-order",
  updateOrder = "update-order",
  changeTable = "change-table",
  changeClient = "change-client",
  updateOrderDetail = "update-order-detail",
  updateOrderDetailsStatus = "update-order-details-status",
  addOrderDetail = "add-order-detail",
  deleteOrderDetail = "delete-order-detail",
  updateqtyDeliveredDetail = "update-qty-delivered-detail",
  deleteOrder = "delete-order",
  payOrder = "pay-order",
  deliverOrder = "deliver-order",
  createInvoice = "create-invoice",
  updateInvoice = "update-invoice",
  deleteInvoice = "delete-invoice",
  updateTable = "update-table",
  createBill = "createBill",
  createSale = "createDirectBill",
  deleteBill = "removeBill",
  updateBill = "updateBill",
  payBillTransaction = "payBillTransaction",
  removeTransaction = "removeTransaction",
}
